language: c
script: asdf plugin-test R https://github.com/cirode/asdf-R.git 'R --version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx